name: build

on:
  push:
    branches: [gha]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: docker
        run: |
          docker version
          docker compose version
          docker-compose-v1 version
