name: build

on:
  push:
    branches: [gha]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: docker
        run: |
          docker version
          docker compose version

      - name: compose-v1
        run: |
          curl -sSL https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64 -o docker-compose-Linux-x86_64
          curl -sSL https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64.sha256 -o docker-compose-Linux-x86_64.sha256
          sha256sum --check docker-compose-Linux-x86_64.sha256
          ./docker-compose-Linux-x86_64 version
